### ISSUE TITLE
typescript compatibility: hashi-vault-js not compatible with type script

### ISSUE THREAD

**Issue by WahilaZlatan** [kyndryl-open-source/hashi-vault-js#15]
hashi-vault-js cannot be compile in typescript returns the following error.

Could not find a declaration file for module 'hashi-vault-js'. 'c:/Users/SICTO-PC/Desktop/apps/ideas-api/node_modules/hashi-vault-js/Vault.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/hashi-vault-js` if it exists or add a new declaration (.d.ts) file containing `declare module 'hashi-vault-js';`ts(7016)

Could you activate this to improve the user experience

**Comment by rod-anami** [comment]
Sorry, could you give the details regarding this one? How are you declaring Vault in your code? Which version are you using? How are you calling the class constructor? Thanks.

**Comment by blairham** [comment]
I found this which uses this package as a dependency, should help with this.
https://npm.io/package/nest-vault
