### ISSUE TITLE
Provide support to read General Secret

### ISSUE THREAD

**Issue by mnadeem** [kyndryl-open-source/hashi-vault-js#20]
**Describe the feature/enhancement**
I should be able to read not just kv/secret engine but also any other for example ad 

I am able to read 
**kv/data/mysql/webapp** 

I am not able to read **ad/creds/app_prod**

It is straight forward in **node-vault**

**Expected behavior**
Anybody should be able to read generic secrets and not just kv secret engine.

**Additional context**
Add any other context about the problem here: Refer https://reachmnadeem.wordpress.com/2022/02/15/hashi-vault-and-nodejs-application/

**Comment by rod-anami** [comment]
Hi @mnadeem , this package is strictly developed to follow the official HashiCorp Vault API documentation. You can check it for the KV-V2 here:
https://www.vaultproject.io/api-docs/secret/kv/kv-v2

As you can see there, although you can change the mount point for the secret engine from `kv` to `ad`, the second tier is determined by the API server which can be either `data`, `config`, or `metadata`. 

So, it would work with `ad/data/creds/app_prod` for sure.

You mentioned `node-vault`, but I was wondering if you really have mounted a KV-V2 secret engine at `ad` root path. Or if you are just doing a call with `node-vault` that will definitely not returning a secret back.

**Comment by mnadeem** [comment]
Hi  @rod4n4m1 

**ad** is not **kv** it is **active directory Secret engine** https://www.vaultproject.io/docs/secrets/ad

If you go to point #4 of Quick setup, ad credentials are automatically mounted at **ad/creds**

<img width="482" alt="image" src="https://user-images.githubusercontent.com/476145/154334256-a2689a6f-92a5-47a3-8837-22dcf3b0acf7.png">

**Comment by mnadeem** [comment]
In essence, I am asking for is there any plan to support **ad secret engine**

**Comment by rod-anami** [comment]
@mnadeem now makes sense, basically the enhancement is to include the `Active Directory Secrets Engine` support in this package.
Reference: https://www.vaultproject.io/api-docs/secret/ad
I'll put it in the queue, it's seems straight forward implementation, the trick is to get hands on a AD test environment.

**Comment by mnadeem** [comment]
Right, Reading **ad** is like **kv** 

You can create local ad, either using [Apache DS](https://docs.craftercms.org/en/3.1/developers/cook-books/how-tos/setting-up-an-ldap-server-for-dev.html) or [openldap](https://www.openldap.org/doc/admin22/quickstart.html)

**Comment by rod-anami** [comment]
I've added an OpenLDAP container as a mockup LDAP server for the testing suite. This enhancement is targeted for `0.4.10`.

**Comment by rod-anami** [comment]
@mnadeem After reading the AD secret engine document in deep, I realize it has a completely different behavior from KV v2. 

It actually generates a credential (password) and saves it to `unicodePwd` attribute inside AD. I managed to create a OpenLDAP instance with some AD schema attributes. But for the whole implementation of all endpoints, it will take more time. I'm re-tagging this to `0.4.11`.

**Comment by rod-anami** [comment]
@mnadeem could you test the functions? It's already available here as a pre-release.

**Comment by rod-anami** [comment]
Closed as already implemented
