### ISSUE TITLE
Could not find a declaration file for module 'hashi-vault-js'.

### ISSUE THREAD

**Issue by WayneShi0928** [kyndryl-open-source/hashi-vault-js#21]
const Vault = require('hashi-vault-js');

there is an eror when I use. I have npm installed the hash-vault-js.

Could not find a declaration file for module 'hashi-vault-js'.
Try `npm i --save-dev @types/hashi-vault-js` if it exists or add a new declaration (.d.ts) file containing `declare module 'hashi-vault-js';`

Thank you.

**Comment by rod-anami** [comment]
Hi @WayneShi0928 thanks for contacting us. Could you elaborate on how are you using this package after installing it? 
Have you installed it by using `npm install hashi-vault-js --save`? Or have you modified the package.json?

**Comment by rod-anami** [comment]
Let me follow up with @WayneShi0928 . Could you please provide details?

**Comment by rod-anami** [comment]
I'm closing it as @WayneShi0928 didn't reply back. Thanks
