### ISSUE TITLE
Ability to fetch latest available secret version

### ISSUE THREAD

**Issue by mb-shorai** [kyndryl-open-source/hashi-vault-js#23]
**Describe the feature/enhancement**
At this moment, if the latest KV secret version is deleted, fetching the secret with `readKVSecret` results in 404. The module should provide a way to fetch the latest available secret version.

**Expected behavior**
`readKVSecret` fetches the latest available (not deleted) secret version automatically **and**/**or** the module provides a separate method to obtain secret's metadata. Based on metadata, a user would be able to list all secret versions and their state in order to select the latest suitable version manually.

**Comment by rod-anami** [comment]
@mb-shorai Sorry for the long run, I tested it here and you can simply call the function like this:

`const data = await vault.readKVSecret(Token, SecretName, **null**, RootPath);`

If you don't pass the version, it will bring the latest one as a default behavior.

Let me if that resolves your need. Thanks

**Comment by rod-anami** [comment]
Since I didn't hear back from you, I'm closing this issue. Thanks
