### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by xenoterracide** [kyndryl-open-source/hashi-vault-js#24]
it doesn't look like there's any typescript definitions, please add

**Comment by rod-anami** [comment]
Hi @xenoterracide, enabling **types** inside this module is not so trivial, you can see alternative solutions to use it *as is* [here](https://stackoverflow.com/questions/38224232/how-to-consume-npm-modules-from-typescript).

I think it doesn't hurt to add support for `typescript`, but it's not a priority unless we have a volunteer willing doing that.

**Comment by phr3nzy** [comment]
I can work on adding types. Will send PR when ready 👍🏾

**Comment by rod-anami** [comment]
@phr3nzy Excellent, thanks a lot for stepping in. I will release `0.4.11` which expands AD functionalities next week just for your information.

**Comment by phr3nzy** [comment]
Progress can be followed of the typings here: https://github.com/phr3nzy/hashi-vault-js/pull/1

**Comment by phr3nzy** [comment]
PR for types https://github.com/rod4n4m1/hashi-vault-js/pull/25

**Comment by rod-anami** [comment]
@phr3nzy Awesome! Thanks so much! I'll analyze it over the weekend and merge. Also, adding your name to the contributors hall.

**Comment by rod-anami** [comment]
Closed as it was merged with main branch
