### ISSUE TITLE
'npm install hashi-corp-js' return 404 ERR

### ISSUE THREAD

**Issue by HuangRongcun** [kyndryl-open-source/hashi-vault-js#3]
npm install hashi-corp-js

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/hashi-corp-js - Not found
npm ERR! 404
npm ERR! 404  'hashi-corp-js@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/***/.npm/_logs/2020-10-21T02_07_58_872Z-debug.log

**Comment by rod-anami** [comment]
Sorry, this is a typo in the documentation, please use `npm install hashi-vault-js`. I'll fix it on `0.3.13`.

**Comment by rod-anami** [comment]
Tagged for `0.3.13`
