### ISSUE TITLE
Adjust TypeScript types

### ISSUE THREAD

**Issue by jstnklnr** [kyndryl-open-source/hashi-vault-js#31]
**Describe the feature/enhancement**
The `VaultConfig` type could contain the `cert`, `key` and `cacert` as optional, because they are not needed for development mode.

`params` in `healthCheck` should probably also be optional since they are not needed in the example given in the README.md.

`ReadKVSecretResponse` is an empty object `{}` should be something like this:

```
export type ReadKVSecretResponse = {
    data: Record<string, any>;
    metadata: {
        created_time: string;
        custom_metadata: Record<string, any> | null;
        deletion_time: string;
        destroyed: boolean;
        version: number;
    }
} | ErrorResponse;
```

**Expected behavior**
This would enable typescript and editors to know the correct types to not throw errors when compiling / making correct intellisense suggestions.

Thank you for your work :)

**Comment by rod-anami** [comment]
@jstnklnr Thanks for pointing this out. I just put it in the roadmap. Let me know if you want to do PR yourself for it. Regards,

**Comment by phr3nzy** [comment]
I can pick this up. Wanted to do some refactors on the typings anyway :)

**Comment by rod-anami** [comment]
Thanks a lot @phr3nzy !

**Comment by phr3nzy** [comment]
Here it is.. https://github.com/rod4n4m1/hashi-vault-js/pull/35

On another note: I thought it'd be much more efficient if I create another request for the overall refactoring of the types. Meanwhile, can I do another PR to create a linter & formatter precommit hook? Just enforces style and makes sure we don't commit wrong things. We can also extend it to run unit tests for code on each hook. What do you think? @rod4n4m1

**Comment by rod-anami** [comment]
@phr3nzy  Sounds excellent to me. Will close this one as fixed.
