### ISSUE TITLE
Incorrect Types

### ISSUE THREAD

**Issue by Intevel** [kyndryl-open-source/hashi-vault-js#38]
## Incorrect Types

Most types are written with `type`, which is basically correct. However, for object types that represent a data structure, you should use `interface` and not `type`. `type` should be used for primitives.

## Example of this problem

```
const vaultData = await vault.readKVSecret(vaultToken, `secret`);

const accessKey = vaultData.data.accessKey;
// -> `data` does not exist on type ReadKVSecretResponse
```

And If I want to define my own type for ReadKVSecretResponse, I can't, its always `Record<string, unknown>`, this should be generic.

## Solution

Refactoring the types, use `interface` for objects, and use [Generic Types](https://www.typescriptlang.org/docs/handbook/2/generics.html) for responses.

I can make PR for that @rod4n4m1

**Comment by rod-anami** [comment]
@Intevel Seems interesting proposal, not completely sure what's the best here.

@phr3nzy Hi Osama, what do you think?

**Comment by phr3nzy** [comment]
Using `interface` and Generics is the right direction. I'll put those on the proposal I'm working on. Cheers!

**Comment by agentschmitt** [comment]
I have the same error: `data` does not exist on type ReadKVSecretResponse

```
const response = await vault.readKVSecret(token, secretName, undefined, secretMount);
console.log(response.data);
```

I think is caused by ReadKVSecretResponse having a multi-type defintion.

```
export type ReadKVSecretResponse = {
	data: Record<string, unknown>;
	metadata: {
		created_time: string;
		custom_metadata: Record<string, unknown> | null;
		deletion_time: string;
		destroyed: boolean;
		version: number;
	}
} | ErrorResponse;
```

Only workaround i found is doing an cast. Also the cast is bit ugly as the response defintion uses an anonymous type to define its fields so i would need to copy the whole definition...

```
const response = await vault.readKVSecret(token, secretName, undefined, secretMount);
const result = response as { data: Record<string, unknown> };
console.log(result.data);
```

**Comment by Intevel** [comment]
I think the types should get refactored. We remove the ErrorResponse Type from the definitions, use interface for type objects, and then we also can implement Generic Types.

@agentschmitt @rod4n4m1 As I said I can make PR for that.

**Comment by rod-anami** [comment]
@Intevel Sure, could you put an example here? I want to create a pattern for all types, so we avoid inconsistencies in the next releases.

**Comment by abcfy2** [comment]
```ts
const response = await vault.readKVSecret(token, secretName, undefined, secretMount);
if ('data' in response) {
  // response should be: {
 //	data: Record<string, unknown>;
 //	metadata: {
 //		created_time: string;
 //		custom_metadata: Record<string, unknown> | null;
 //		deletion_time: string;
 //		destroyed: boolean;
 //		version: number;
 //	}
  const data = response.data;
} else {
  // response should be ErrorResponse
  throw new Error(JSON.stringify(response));
}
```

**Comment by Intevel** [comment]
> ```ts
> 
> const response = await vault.readKVSecret(token, secretName, undefined, secretMount);
> 
> if ('data' in response) {
> 
>   // response should be: {
> 
>  //	data: Record<string, unknown>;
> 
>  //	metadata: {
> 
>  //		created_time: string;
> 
>  //		custom_metadata: Record<string, unknown> | null;
> 
>  //		deletion_time: string;
> 
>  //		destroyed: boolean;
> 
>  //		version: number;
> 
>  //	}
> 
>   const data = response.data;
> 
> } else {
> 
>   // response should be ErrorResponse
> 
>   throw new Error(JSON.stringify(response));
> 
> }
> 
> ```

This way isn't clean, generic types are the best for this case. @rod4n4m1

**Comment by rod-anami** [comment]
@Intevel I agree we need to refactor `Vault.d.ts`. 

This is what we have today (getting one example):

```typescript
export type ReadKVSecretResponse = {
	data: Record<string, unknown>;
	metadata: {
		created_time: string;
		custom_metadata: Record<string, unknown> | null;
		deletion_time: string;
		destroyed: boolean;
		version: number;
	}
} | ErrorResponse;
...
readKVEngineConfig(token: string, mount?: string): Promise<ReadKVEngineConfigResponse>;
...
```

Would this be the refactored code?

```typescript
interface ReadKVEngineConfigResponse {
  <Type>(data: Type, metadata: Type): Type;
};
...
readKVEngineConfig<Type>(token: string, mount?: string): Promise<ReadKVEngineConfigResponse>;
...
```
I'm not versed on TS.

**Comment by Intevel** [comment]
This looks right.

**Comment by Intevel** [comment]
Actually I think we should refactor this whole project to a typescript project @rod4n4m1 What do you think? I can create a PR for that.

**Comment by rod-anami** [comment]
@Intevel yes, I think it's good direction, but first we need to fix the types error. Would you be able to help with the refactoring of `Vault.d.ts`?

**Comment by phr3nzy** [comment]
I agree with @Intevel and have begun migrating to TS. Will issue a PR ASAP

P.S. apologies for my disappearance, just finished settling in 😄

**Comment by Intevel** [comment]
@phr3nzy If you need any help, I can contribute to your PR.

**Comment by phr3nzy** [comment]
@Intevel Thank you, will let you know when it's up!

**Comment by rod-anami** [comment]
Folks, instead of re-coding all the interfaces, I just used the TypeScript compiler to generate the .d.ts files from the JavaScript code through JSDoc syntax.
https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html
Please check if that's good enough!

**Comment by Intevel** [comment]
> Folks, instead of re-coding all the interfaces, I just used the TypeScript compiler to generate the .d.ts files from the JavaScript code through JSDoc syntax. https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html Please check if that's good enough!

Actually no, there is a lot of `any` and thats not good, thats not really good typed. And we also thought about using Generic Types, we should write the types instead of generating wrong types.

**Comment by rod-anami** [comment]
@Intevel the many **any** types are due to the lack of JSDoc for the class constructor, I spent long hours linting the JSDoc for the compiler, but I forgot the put them on the other parts. 

It would be awesome if we could automate this types generation. I need help if we go with the <T> generic types and use only interfaces.

**Comment by Intevel** [comment]
Surely I can help with that and make a PR.

**Comment by rod-anami** [comment]
Closing it due lack of volunteers.
