### ISSUE TITLE
Shoud reject an Error object

### ISSUE THREAD

**Issue by Richie765** [kyndryl-open-source/hashi-vault-js#4]
**Describe the bug**
When a promise is rejected, its value should be a standard error object. Currently it is not so it does not contain a stack-trace. This way it is not possible to pinpoint where the problem happened.

**To Reproduce**
```javascript
async function main() {
  try {
    // Make this an error, e.g. invalid token, etc
    const data = await vault.createKVSecret(token, 'hello', { hello: 'world' });
  }
  catch(err) {
    console.log(err);
  }
}
```

The result I got is:
```
{
  status: 400,
  data: {
    errors: [ 'check-and-set parameter did not match the current version' ]
  },
  headers: {
    'cache-control': 'no-store',
    'content-type': 'application/json',
    date: 'Sat, 12 Dec 2020 10:19:53 GMT',
    'content-length': '73',
    connection: 'close'
  }
}
```

As you see, no stack trace etc.

**Expected behavior**
It should be a standard Error object, which contains a stack trace where the error ocured.

**Additional context**
When you reject a promise, you should always do something like:
```javascript
new Promise((resolve, reject) => {
  reject(new Error("Whoops!"));
})
```

This way you "wrap" your error information inside an Error object and you get the stack-trace etc included.

For instance, when catching the above error I get this result:
```
Error: Whoops!
    at /develop/tests/api/vault/hashi-vault.js:61:12
    at new Promise (<anonymous>)
    at test (/develop/tests/api/vault/hashi-vault.js:60:10)
    at main (develop/tests/api/vault/hashi-vault.js:73:11)
    at Object.<anonymous> (/develop/tests/api/vault/hashi-vault.js:81:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
```

Very clear.

Bonus: Please don't parse the Axios error, just reject it as it is. It is already an Error object so you can just do reject(axiosError). By not parsing it, you just pass on the full Axios error with all the information that Axios provides.

See also:
* https://javascript.info/promise-error-handling

Bonus 2: sorry to keep adding to this bug. You can really simplify your code a lot. There is no need to wrap everything in a "new Promise" at all. Look at this example:

Your code:
```javascript
  async destroyVersionsKVSecret(token, name, versions) {
    return new Promise((resolve, reject) => {
      const Options = {
        url: `/${this.rootPath}/${config.destroyPath}/${name}`,
        method: 'post',
        headers: {
          "X-Vault-Token": token
        },
        data: {
          "versions": versions
        }
      };
      this.instance(Options).then(function(response){
        resolve(parseAxiosResponse(response));
      }).catch(function(error){
        reject(parseAxiosError(error));
      });
    });
  }
```

How it should be:
```javascript
  async destroyVersionsKVSecret(token, name, versions) {
      const Options = {
        url: `/${this.rootPath}/${config.destroyPath}/${name}`,
        method: 'post',
        headers: {
          "X-Vault-Token": token
        },
        data: {
          "versions": versions
        }
      };

      const response = await this.instance(Options);
      return parseAxiosResponse(response);
  }
```

As you see, you don't need to do a "new Promise", it is absolutely not needed. You can get rid of the obsolete "then/catch" stuff. You don't even have to do anything with the error from Axios, as it will automatically fall through to the caller's catch statement. And, as you see, no parsing of the Axios error as well.

Good luck! Hope I wasn't too obnoxious!

**Comment by rod-anami** [comment]
Thanks @Richie765 ! This is well explained and I see value on following the proposed path. I'll address this on `0.3.18` version. I was not satisfied on doing another **Promise** on top of Axios promise, it was something inherited from previous  `request` package usage.
