### ISSUE TITLE
Totp secret engine with typescript using hashi-vault-js package 

### ISSUE THREAD

**Issue by jeetdetroja** [kyndryl-open-source/hashi-vault-js#43]
I am using your module for the api implementation in typescript.
but i am facing somr issue in totp secret engine.

how can i read the otp generated by the totp secret engine of the vault.

for reading secrets i am using readKVSecret(); method but same wont work for the totp

**Comment by rod-anami** [comment]
Hi @jeetdetroja I don't think we implemented TOTP secret engine yet.

Are you talking about this one?

https://developer.hashicorp.com/vault/api-docs/secret/totp

If so, we can add this to the queue for a future release.

Thanks

**Comment by rod-anami** [comment]
@jeetdetroja Could you confirm the secret engine above? Thanks

**Comment by rod-anami** [comment]
I'm closing this as there's no answer. Thanks
