### ISSUE TITLE
createToken always creates renewable token

### ISSUE THREAD

**Issue by Richie765** [kyndryl-open-source/hashi-vault-js#5]
**Describe the bug**
https://github.com/rod4n4m1/hashi-vault-js/blob/ebb1f73c39e269229d2005985b29a40d15de7b25/Vault.js#L296

**Additional context**
```jaavscript
false || true == true
```

**Comment by rod-anami** [comment]
Thanks @Richie765, this a nice catch! Do you mind if I mention you as a contributor to this package? I'll address this bug in `0.3.19`

**Comment by Richie765** [comment]
Sure you may mention me. I'm just glad you fixed the other issue so quickly as I like this package more than the other one.

**Comment by rod-anami** [comment]
0.3.19 RC has been published

**Comment by Richie765** [comment]
https://github.com/rod4n4m1/hashi-vault-js/blob/6ecc8a1e0ea6da57a0afc7cbe5aeb021b7986ce6/Vault.js#L294-L296

Actually I think this does not fix the issue. `typeof` returns a string, so `undefined` should be between quotes. I don't think `typeof` can ever return undefined.

However, there is no need to use `typeof` at all. You can just do:

```javascript
// when default is false
          no_parent: noParent,

// or (if you want to be sure it will be boolean - I rarely do this)
          no_parent: !!noParent,

// when default is true:
          renewable: renewable == undefined ? true : renewable,

// or (valid but less clear)
          renewable: renewable == undefined || renewable,

// You can also do the following, but support is just starting
          renewable: renewable ?? true,
```

By using '==' it will also match `null`, which I think is ok in this case. If you use `===` it will only match `undefined`. As a side note, I general I believe JS developers use `===` way too often. In my opinion, most of the times `==` is the way to go, and `===` should be the exception when it is really needed (which is rarely so).

I hope it helps!

**Comment by rod-anami** [comment]
Thanks @Richie765 ! I'm reopening this one. Yep, it makes sense to me now that `undefined` is not going to happen with the way I built this interface, it's either `null` or `defined` with a value. So, I'll go with `==` operator.

I love the new [nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) operator (??), but it's only supported in the **node.js v14**. I intend to move to v14 this year.

**Comment by rod-anami** [comment]
Tagged for `0.3.21`

**Comment by Richie765** [comment]
@rod4n4m1 Yeah, the ?? operator is great! I'm using it in my internal projects all the time! I was waiting for it for a long time since I was used to the same '//' operator in Perl, that was way back in the stone-age, haha ;-)
Anyways thanks again!
